application: go-startup
version: alpha-001
runtime: go
api_version: go1
threadsafe: yes

handlers:       # static then dynamic

- url: /.*
  script: _go_app

- url: /_ah/spi/.*
  script: _go_app
  secure: always